[package]
name = "path_oram"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8"
ctr = "0.9"
cipher = "0.4"
rand = "0.8"
redis = "0.23"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
indicatif = "0.17"

[dev-dependencies]
criterion = "0.4"
